### ISSUE TITLE
CPU Load over 90%

### ISSUE THREAD

**Issue by SirPrikol** [charuwts/UCRM-Client-Signup#5]
After installing the plugin - strange actions began in the network. Loading the channel within the network has become 2GB / s, it seems that the plug-in scans the network for vulnerabilities, plus there are problems with downloading uplink. At 700 megabit, something is dragging from Chinese IP addresses

**Comment by charuwts** [comment]
@SirPrikol 

This plugin does not scan the network for vulnerabilities and I'm not sure what you mean by dragging from Chinese IP addresses. **The cause is either with UCRM or unrelated**. This plugin is very straightforward in it's implementation, it simply submits a JSON request to itself then creates a client via the UCRM API.

**Comment by SirPrikol** [comment]
I can shoot a video and post it, the problems started after installing this plugin. No, maybe the stars coincided. Now I will try to reinstall and see. I, surely, can be mistaken, since the place where billing is put is Guatemala, and I myself am in Russia. And normal sabotage is possible.

**Comment by charuwts** [comment]
The plugin has no processes that run outside of submitting the form on the public URL. Sorry you're having trouble, but it is extremely unlikely to be related.

**Comment by SirPrikol** [comment]
The plugin itself is great, for the first time this happened. True, I changed the code a bit, since there are extra fields. I apologize in advance if I made a mistake. Therefore, I said, I will check back.
